[build]
command = "npm ci && npx prisma generate && npm run build"
publish = "build/client"

[build.environment]
NODE_ENV = "production"
NETLIFY_CACHE_ID = "prisma-v2"
# Disable Prisma's Netlify detection
NETLIFY = ""
NETLIFY_DEV = ""

[functions]
included_files = ["node_modules/@prisma/client/**", "node_modules/.prisma/**", "prisma/**"]

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames
[[headers]]
for = "/build/*"

[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"
