[build]
command = "npm install && npx prisma generate && npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

[headers.values]

"Cache-Control" = "public, max-age=31560000, immutable"

# Environment variables for Supabase
[build.environment]
  NODE_ENV = "production"
