[build]
command = "rm -rf node_modules/.prisma && npm ci && npx prisma generate && npx prisma db push --accept-data-loss && npm run build"
publish = "build/client"

[functions]
included_files = ["node_modules/@prisma/client/**", "node_modules/.prisma/**", "prisma/**"]

# Force a clean build by invalidating cache
[build.environment]
NODE_ENV = "production"
NETLIFY_CACHE_ID = "prisma-v1"

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

[headers.values]

"Cache-Control" = "public, max-age=31560000, immutable"

# Environment variables for Supabase
[build.environment]
  NODE_ENV = "production"
